# Generated by Django 4.1 on 2022-11-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_Name', models.CharField(max_length=200)),
                ('Mod_Name', models.CharField(max_length=200)),
                ('Desc', models.TextField(max_length=200)),
                ('Plate_number', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Age', models.IntegerField()),
                ('Address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('Contact_Number', models.IntegerField()),
                ('License_Number', models.CharField(max_length=11)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=9, verbose_name='gender')),
                ('car_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.car')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pick_Up', models.CharField(max_length=200)),
                ('Drop_Off', models.CharField(max_length=200)),
                ('customer_booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.customer')),
            ],
        ),
    ]
