# Generated by Django 4.1 on 2022-11-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
