# Generated by Django 4.1 on 2022-11-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Desc',
            field=models.TextField(max_length=500),
        ),
    ]
