# Generated by Django 4.1 on 2022-11-15 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_car_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book', to='base.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='car_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='base.car'),
        ),
    ]
