# Generated by Django 4.1 on 2022-11-23 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_booking_customer_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer_booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='base.customer'),
        ),
    ]
