# Generated by Django 4.1 on 2022-12-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_booking_customer_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
